### ISSUE TITLE
Performance bug: Matrix and Vector should use concrete and not abstract type

### ISSUE THREAD

**Issue by plerouxanyon** [anyonlabs/Snowflake.jl#50]
The Operation, Ket, and Bra use Matrices and Vectors of abstract types. This prevents efficient packed storage and computation. I've attached a PDF with benchmarks of matrix multiplication using abstract type and without.

[MatrixPerformanceBug.pdf](https://github.com/anyonlabs/Snowflake.jl/files/10769321/MatrixPerformanceBug.pdf)

**Comment by alireza-najafi** [comment]
This was fixed in the recent merge.
