### ISSUE TITLE
Stripped down version of Snowflake

### ISSUE THREAD

**Issue by mboisson** [anyonlabs/Snowflake.jl#58]
Currently, the manifest includes a lot of things which do not seem to be critical for using Snowflake
https://github.com/anyonlabs/Snowflake.jl/blob/main/Project.toml

Can we get a stripped down version of the requirements without anything that is not absolutely required ?

**Comment by mboisson** [comment]
Probably removing plots from the requirements would make the package *much* lighter to install.

**Comment by plerouxanyon** [comment]
Hi, 

This is a very good point. We will split the plotting part from `Snowflake.jl` into its package. This looks to align with what other Julia packages are doing. I can't give a firm timeline yet, but this will be done before the first release.

**Comment by plerouxanyon** [comment]
We will track the progress of this issue through https://github.com/anyonlabs/Snowflake.jl/issues/81.
